(require 'docker)
(require 'dockerfile-mode)
(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
(require 'docker-compose-mode)
(require 'docker-tramp-compat)
(set-variable 'docker-tramp-use-names t)
