;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anzu-query-replace
        backward-up-list
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        coffee-dedent-line-backspace
        comment-dwim
        company-indent-or-complete-common
        count-words-region
        dabbrev-expand
        delete-horizontal-space
        ee-duplicate-this-line
        electric-newline-and-maybe-indent
        elisp-last-sexp-toggle-display
        emmet-expand-line
        ignore
        ik:camerize<->decamelize-thing-ad-point-or-region
        indent-for-tab-command
        insert-date
        kill-region
        lsp-ui-doc--handle-mouse-movement
        markdown-outdent-or-delete
        mouse-set-region
        org-cycle
        org-delete-char
        org-force-self-insert
        org-kill-line
        org-metaleft
        org-metaright
        org-open-line
        org-self-insert-command
        org-yank
        powershell-indent-line
        rst-adjust
        seq-end
        seq-home
        sgml-slash
        sh-assignment
        wdired--self-insert
        wdired-downcase-word
        wdired-finish-edit
        web-mode-comment-or-uncomment
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ))
