(when (or
       ;; peccu-p
       win-env-p
       wsl-p
       )
  ;; generated by ChatGPT
  ;; https://chatgpt.com/share/0ca4b7b0-ecc6-41c3-9454-9588aefba8e4

  (defun my/copy-latest-file-and-insert-org-link (source-dir target-dir)
    "Copy the latest file from SOURCE-DIR to a subdirectory of TARGET-DIR based on the current date,
and insert the org-mode image link at point."
    (interactive "DSource directory: \nDTarget directory: ")
    (let* ((files (directory-files source-dir t "^[^.].*"))
           (latest-file (car (sort files (lambda (a b) (time-less-p (nth 5 (file-attributes b))
                                                                    (nth 5 (file-attributes a)))))))
           (file-name (file-name-nondirectory latest-file))
           (current-year (format-time-string "%Y"))
           (current-month (format-time-string "%m"))
           (target-subdir (expand-file-name (concat current-year "/" current-month) target-dir))
           (target-path (expand-file-name file-name target-subdir)))
      (unless (file-directory-p target-subdir)
        (make-directory target-subdir t))
      (copy-file latest-file target-path t)
      (insert (format "[[file:%s]]" target-path))))

  (defun my/insert-image-like-logsec ()
    (interactive)
    (my/copy-latest-file-and-insert-org-link "~/Work/ScreenCapture" "~/Documents/LogSeq/assets/"))

  (global-set-key (kbd "M-V") 'my/insert-image-like-logsec)

  ;; you can show image inline in org-mode
  ;; (add-hook 'org-mode-hook 'org-display-inline-images)
  ;; M-x org-toggle-inline-images (C-c C-x C-v)
  ;; M-x org-display-inline-images
  ;; M-x org-remove-inline-images
  )
